site_name: Amoglang
site_author: KittyBorgX
site_description: >-
  Is this language sus?
repo_name: KittyBorgX/amoglang
repo_url: https://github.com/KittyBorgX/amoglang

copyright: Copyright &copy; 2021 KittyBorgX

plugins:
  - search
theme:
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  name: material
  features:
    - navigation.sections
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KittyBorgX/amoglang
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xfnnEVyCgv

nav:
  - Home: index.md
  - Documentation:
      - Getting Started: docs/getstarted.md
      - Installation: docs/install.md
      - About: docs/about.md

edit_uri: edit/main/docs
